package io.matthewbelongia.models;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.sql.Timestamp;

/**
 * Created by matthewb on 6/15/16.
 */
@Entity
@Table(name = "tab")
public class Tab {


    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each tab in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    // The tab's empid
    @NotNull
    private String empid;

    // The tab's name
    @NotNull
    private String name;

    // The tab's location
    @NotNull
    private String location;

    // The tab's card
    @NotNull
    private String card;

    // The tab's total

    private Double total;

    // The tab's card
    @NotNull
    private Timestamp date;



    // ------------------------
    // PUBLIC METHODS
    // ------------------------

    public Tab() { }

    public Tab(long id) {
        this.id = id;
    }

    public Tab(String empid, String name,String location,String card, Timestamp date) {
        this.empid = empid;
        this.name = name;
        this.location = location;
        this.card = card;
        this.total = null;
        this.date = date;
    }

    // Getter and setter methods


    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getEmpId() {
        return empid;
    }

    public void setEmpId(String empid) {
        this.empid = empid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getCard() {
        return card;
    }

    public void setCard(String card) {
        this.card = card;
    }

    public Double getTotal() {
        return total;
    }

    public void setTotal(Double total) {
        this.total = total;
    }

    public Timestamp getTimestamp() {
        return date;
    }

    public void setTimestamp(Timestamp date) {
        this.date = date;
    }
} // class Tab


