package io.matthewbelongia.models;


import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.sql.Timestamp;

/**
 * Created by matthewb on 6/15/16.
 */
@Entity
@Table(name = "tabitem")
public class TabItem {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each tabitem in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    //The tabItem's tabid
    @NotNull
    private long tabid;

    @NotNull
    private long cigarid;

    @NotNull
    private Double retail;

    @NotNull
    private long quantity;

    @NotNull
    private long discount;

    @NotNull
    private Double finalamount;

    @NotNull
    private Timestamp timestamp;

    @NotNull
    private long coalcount;

    @NotNull
    private String hookahbuilder;

    @NotNull
    private String salesemployeeid;

    // ------------------------
    // PUBLIC METHODS
    // ------------------------

    public TabItem(){}

    public TabItem(long id){this.id = id;}

    public TabItem(Long tabid,Long cigarid, Double retail,Long quantity,Long discount,Double finalamount,
                   Timestamp timestamp,Long coalcount,String hookahbuilder,String salesemployeeid){
        this.tabid = tabid;
        this.cigarid = cigarid;
        this.retail = retail;
        this.quantity = quantity;
        this.discount = discount;
        this.finalamount = finalamount;
        this.timestamp = timestamp;
        this.coalcount = coalcount;
        this.hookahbuilder = hookahbuilder;
        this.salesemployeeid = salesemployeeid;
    }

    // Getter and setter methods


    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long gettabid() {
        return tabid;
    }

    public void settabid(long tabid) {
        this.tabid = tabid;
    }

    public long getCigarid() {
        return cigarid;
    }

    public void setCigarid(long cigarid) {
        this.cigarid = cigarid;
    }

    public Double getRetail() {
        return retail;
    }

    public void setRetail(Double retail) {
        this.retail = retail;
    }

    public long getQuantity() {
        return quantity;
    }

    public void setQuantity(long quantity) {
        this.quantity = quantity;
    }

    public long getDiscount() {
        return discount;
    }

    public void setDiscount(long discount) {
        this.discount = discount;
    }

    public Double getFinalamount() {
        return finalamount;
    }

    public void setFinalamount(Double finalamount) {
        this.finalamount = finalamount;
    }

    public Timestamp getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Timestamp timestamp) {
        this.timestamp = timestamp;
    }

    public long getCoalcount() {
        return coalcount;
    }

    public void setCoalcount(long coalcount) {
        this.coalcount = coalcount;
    }

    public String getHookahbuilder() {
        return hookahbuilder;
    }

    public void setHookahbuilder(String hookahbuilder) {
        this.hookahbuilder = hookahbuilder;
    }

    public String getSalesemployeeid() {
        return salesemployeeid;
    }

    public void setSalesemployeeid(String salesemployeeid) {
        this.salesemployeeid = salesemployeeid;
    }
}
